version: '3.9'

x-env: &default-env
  DATABASE_URL: postgres://postgres:password@postgres:5432/postgres

volumes:
  pg_data: {}

services:
  postgres:
    image: postgres:11.8
    environment:
      # for development only!
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  django:
    build: .
    image: django_news_nginx
    restart: on-failure
    environment: *default-env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:8113"

  redis:
    image: redis:alpine
    container_name: redis_alpine
    ports:
      - "6379:6379"
