version: '3.4'

x-env: &default-env
  DATABASE_URL: postgres://postgres:password@postgres:5432/postgres

volumes:
  pg_data: {}

services:
  postgres:
    image: postgres:11.8
    environment:
      # for development only!
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  django:
    build:
      context: .
      dockerfile: django.dockerfile
    restart: on-failure
    privileged: true
    environment: *default-env
    depends_on:
      - postgres
    volumes:
      - ./news:/app
    ports:
      - '80:8000'
    command: /start-django
